version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: nest-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    command: npm run start:prod
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vite-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend
