name: CI - Build Fullstack App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Clonar el repositorio
        uses: actions/checkout@v3

      - name: 🧰 Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: 🐳 Construir imagen del backend
        run: docker build -t backend-image ./backend

      - name: 🐳 Construir imagen del frontend
        run: docker build -t frontend-image ./frontend
